# Generated by Django 2.2 on 2019-05-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.TextField(),
        ),
    ]
